### ISSUE TITLE
sort icons in results are not shown

### ISSUE THREAD

**Issue by gmarcon** [JustCarmen/webtrees-theme-justlight#103]
I just upgraded to the latest version of the theme, the sort icons in results are not shown anymore.
It seems that somehow the original Unicode character for up/down gets transcoded.

This is what I see:
<img width="612" alt="image" src="https://user-images.githubusercontent.com/1568716/153715069-b2334194-0a03-49f3-af24-e1bf44234b41.png">

Inspecting with Chrome DevTools I see a \f0dc content instead of the original ↓ character:
<img width="483" alt="image" src="https://user-images.githubusercontent.com/1568716/153715150-443ae376-54c0-48d8-96b2-44ce05b5373e.png">

Thank you for the help and the great theme!

**Comment by JustCarmen** [comment]
Thanks. Update was done due to data protection issues with FontAwesome. `
See: https://www.webtrees.net/index.php/en/forum/4-customising/36509-justlight-theme-and-data-protection

But I overlooked those icons. Must have missed something.

**Comment by gmarcon** [comment]
I confirm that downgrading to 2.1.2.1 fixes the icons. I will keep this version for now.
I noticed some other broken icons so it is probably a general issue with all icons and using a local copy of font awesome.

Thank you for your very quick support!

**Comment by mpwt** [comment]
Could it be, that the solid.min.css is missing now? This was a file linked from cloudflare server.

**Comment by JustCarmen** [comment]
`Could it be, that the solid.min.css is missing now? This was a file linked from cloudflare server.`

Yes, it is. But I can't use that file locally, because I cannot link directly to the resources folder (with the fonts) from css. But since I thought it was not used anyway I didn't search for an alternative solution. But I was wrong. Missed a few icons depending on it.

I've solved it now. I will draft a new release soon.
