### ISSUE TITLE
visibility of links (justBlack)

### ISSUE THREAD

**Issue by LarsRabe** [JustCarmen/webtrees-theme-justlight#135]
In the justLight-theme links are blue-ish. In the justBlack-theme they're kind of grey-ish and not really good visible:
![links_1](https://user-images.githubusercontent.com/119816325/209975147-523f83b0-55c4-4809-9da9-bc6c89c935f0.jpg)

On other screens they're better visible:
![links_2](https://user-images.githubusercontent.com/119816325/209975260-619847c3-dbf4-49a5-b21d-8689abbba3d7.jpg)

It seems in the second screenshot the links are bold? Making the links manually bold (e.g. in the html-block) enhances the visibility.
Could this be the standardized behaviour in the justBlack-theme? Or would it be better to use a color as in the justLight-theme (e.g. orange-ish)?

**Comment by JustCarmen** [comment]
Styling links in webtrees is difficult. Most pages contain a lot of links, most text consists mostly of links. Giving the links an distinctive color will give your website a restless look.

This theme mostly follows webtrees default link styling. Take a look at the default webtrees theme. You'll see that you need to hover over a link to see the color changing. In the specific part you are showing (the statistics block), the links are made bold by webtrees., but that is not because they are a link, but because they are a label.

But you can use the orange color to format the links in your html block by using the class 'text-primary'. Select the text you want to have the link on, then click on the link icon or use ctrl K. Go to the tab 'advanced' to set the appropriate class:

![image](https://user-images.githubusercontent.com/5641963/210041847-529fdd90-612f-41a5-bbf9-357e0faf742a.png)

**Comment by LarsRabe** [comment]
@JustCarmen 
Works like a charm! 

Thank you for this amazing work and all the best wishes for 2023.

BTW, can I somehow buy you a "koffie met appeltaart"?

Lars

**Comment by LarsRabe** [comment]
> In fact you can :). There is a donate button in the Readme section of the code tab,
Aaargh, didn't see that.
