### ISSUE TITLE
Feature Request: Graphics

### ISSUE THREAD

**Issue by heiler** [JustCarmen/webtrees-theme-justlight#57]
Would it be possible to have the same graphics as in the Webtrees Theme, please see encl. screenshot?
Kind regards

![Bildschirmfoto vom 2020-10-09 14-42-08](https://user-images.githubusercontent.com/2920260/95584738-7b6e2c00-0a3e-11eb-8c9a-2adadf4ddc90.png)

**Comment by JustCarmen** [comment]
Are these default webtrees icons? I cannot find them. Where are these icons located? Are you sure they are not part of a custom module?

Give me a link to a page where I can see them so I can find out where they came from.

**Comment by heiler** [comment]
Here is an example
[https://www.heiler-ahnen.de/webtrees/tree/heiler/individual/I0160/Theodor-Heiler#](https://www.heiler-ahnen.de/webtrees/tree/heiler/individual/I0160/Theodor-Heiler#)
You can find the graphics in Clouds, Colors, Webtrees and Xenea.

**Comment by ric2016** [comment]
Most of these icons are in fact added via custom modules.

How custom modules from different sources interact is fundamentally undefined. I think it makes more sense though for custom modules providing specific functionality (Gov4Webtrees in this case) to adapt to certain 'well-known' custom themes, rather than the other way around.

I have actually done this already in my custom modules - The additional icons used for the 'JustLight' theme match the ones used in the 'minimal' theme, as that seems to be the basis for the icons used in the 'JustLight' theme. So there is already a consistent look & feel.

@JustCarmen: If you decide to replace e.g. the map link icons as requested (this would affect the original Facts & Events tab), I'll adjust my custom modules accordingly.

**Comment by JustCarmen** [comment]
I suspected these icons came from a custom module but I wasn't absolutely sure.

>  I think it makes more sense though for custom modules providing specific functionality (Gov4Webtrees in this case) to adapt to certain 'well-known' custom themes, rather than the other way around.

I agree. I've done the same thing within the Fancy imagebar module where I have provided the layout for the Rural theme (which is not mine).

Thanks @ric2016 for supporting the JustLight theme in your modules.

> If you decide to replace e.g. the map link icons as requested (this would affect the original Facts & Events tab), I'll adjust my custom modules accordingly.

I don't think it is necessary since you've provided the support for this theme in your module. So I will close this issue.

**Comment by heiler** [comment]
But IMHO it is not nice and not functional.
