### ISSUE TITLE
Details text is cropped in pedigree trees

### ISSUE THREAD

**Issue by frenzeldk** [JustCarmen/webtrees-theme-justlight#59]
When looking at standard pedigree trees the details text is cropped. See below image as an example. For most people the text is only partially cropped, but with long place names it is cropped completely (Else Blohm in the shown image).

This issue seems to affect all charts where this type of cards is used (descendants, family book, etc.).

![image](https://user-images.githubusercontent.com/1295777/95730285-5536cf00-0c7e-11eb-9a94-b565fe9018f4.png)

**Comment by JustCarmen** [comment]
I've tried to, but I can't reproduce this error. Do you have a link to a webpage where this occurs?

**Comment by frenzeldk** [comment]
@JustCarmen yes, of course. Here is an example https://familie.frenzel.dk/tree/Frenzel/pedigree-right-4/X1576
It renders like this on my screen (22" 1680x1050)
![image](https://user-images.githubusercontent.com/1295777/96716229-0c30fa00-13a5-11eb-9892-a3fec2f8698c.png)

**Comment by mpwt** [comment]
Maybe the boxes are defined in a fixed heigh. 

Have you ever tried to shorten the place names to f.i. the first part? This can be set under > Control panel > Manage family trees > Preferences and makes the place names more readable.

**Comment by JustCarmen** [comment]
> Maybe the boxes are defined in a fixed heigh.

No they are not. Normally the boxes should enlarge with the content.  On my testsite they do, even with full place names. But the provided link of @frenzeldk shows a different layout with fixed height boxes. 

By the way the second screenshot is from the colors theme, but at your site switching to the JustLight theme shows the same cropped boxes. So it is definitely a conflict somewhere.

Looking further with Chrome DevTools (F12) I see you are loading after the Justlight theme to extra modules:
- webtrees-trees-view-full-screen and
- custom-css

Disabling the latter solves the problem.

The custom-css module has set a fixed height on the boxes while the JustLight theme didn't (on purpose). And I think there should not be a fixed height on the boxes because you will ran into the problem as described.

So you should ask @makitso for help: https://github.com/makitso/custom-css/issues

**Comment by makitso** [comment]
Yes, custom-css does fix the sizes of the person box for consistency across all charts.  However, there appears to be something else going on with your example above (I could not access your site).  Many of the other style fixes, that allow the data in the person box to fit the box, seem to not be working.  There is probably another conflict between custom.css and justlight.  This is the reason I have the disclaimer on github saying its only for webtrees standard themes.

**Comment by makitso** [comment]
I have upgraded custom.css to version 1.0.8 so that it plays nicer with non-standard themes such as justlight.

**Comment by JustCarmen** [comment]
Thank you Rob!

**Comment by frenzeldk** [comment]
Thanks @JustCarmen and @makitso for finding and fixing this bug. I hadn't thought about the fact, that I have custom.css installed.

**Comment by makitso** [comment]
@frenzeldk, version 1.0.8 of custom.css has code to allow the person box to be correctly rendered when used along with the justlight theme.
