### ISSUE TITLE
place-list: broken layout on mobile phone

### ISSUE THREAD

**Issue by ungeahnt** [JustCarmen/webtrees-theme-justlight#61]
![Screenshot_20201019_080753](https://user-images.githubusercontent.com/28572767/96407676-35555d00-11e2-11eb-919f-83236ffc282b.jpg)

**Comment by JustCarmen** [comment]
Does this happen in the latest (2.0.9) version?

**Comment by JustCarmen** [comment]
Never mind. I've found it. Looks like a bug caused by two independents parts of the page (the column next to the map) and the footer are trying to resize into the small view. I will look into it.

**Comment by JustCarmen** [comment]
I've found out this is not a bug in the JustLight theme but exists in other themes too. Only there it is less visible because the footer is hidden behind the data column (due to the colored background).  The issue is visible in the minimal theme.

I can't fix this. But I think I've done the next best thing by removing the footer at this page when viewing from a small screen.

**Comment by ungeahnt** [comment]
You are right. Sorry, I should have looked closer first.

The problem exists in the default themes when you activate OpenStreet maps. Without maps the layout is fine.
