### ISSUE TITLE
Support bootstrap themes?

### ISSUE THREAD

**Issue by nateswart** [JustCarmen/webtrees-theme-justlight#67]
Do you have any recommendations on how to best use bootstrap themes (or any plans to support them), specifically for webtrees 2.x?

For example: https://bootswatch.com

**Comment by JustCarmen** [comment]
It doesn't work out of the box, but you could use the (release version of the) JustLight theme as a start. Rename the folder and adjust the title in the file module.php. Download the css of the theme you want to use, copy it to the folder resources/css and point to it from the file module.php (function stylesheets). Remove superfluous parts from the module.php file and you'll have a start.

It need some adjustments though because some css rules from the derived theme are stronger than the ones in the newly added bootswatch theme. So you need to adjust the css. Most easiest way will be probably to add "!important" (without the quotes) behind some css rules to make them stronger.

However, if you know how to code you could start with the scss version of the bootswatch theme of your choice. This gives you more flexibility. In that case you could also use the JustLight theme (master branche or source code from the latest release) as a start.

Good luck.
